### ISSUE TITLE
missing driver for FATFS

### ISSUE THREAD

**Issue by sumit809** [PICmajster/PIC32MM_FATFS_ILI9341#1]
Hi,

I think drva.h and drva.c (or whichever name you had given while configuring FATFS in mcc) is missing in the fatfs directory. Actually it contains functions like 
`bool DRVA_SectorWrite(uint32_t sector_address, const uint8_t* buffer, uint16_t sector_count)`
`bool DRVA_SectorRead(uint32_t sector_address, uint8_t* buffer, uint16_t sector_count)`
What's the reason behind it?

**Comment by PICmajster** [comment]
I don't use these functions in my sample program. I don't understand why they should be there :)

**Comment by sumit809** [comment]
Okay! So I saw that in diskio.c you have pointed out to your own SD card driver for SectorRead and SectorWrite 
Any Idea how can I do it for External Flash Winbond W25Q32 instead of SD card?

Thanks!
Sumit

**Comment by PICmajster** [comment]
I haven't practiced external flash memory yet. I'd probably do it, but I have a lot of work to do now.
forgive me Sumit

**Comment by sumit809** [comment]
You are forgiven @PICmajster 😜
All the best 👍
